name: Call Reusable Code Scanning Workflow
on:
    workflow_dispatch:
    push:
        branches: spike/7108-reusable-workflows
jobs:
  call-reusable-code-scanning-workflow:
    uses: ministryofjustice/modernisation-platform-terraform-module-template/.github/workflows/reusable-code-scanning.yml@2a4bd3a774cf1c85fcda482003943ff2258dc0ce
    secrets: inherit
