name: "Format Code: ensure code formatting guidelines are met"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
permissions: {}

jobs:
  format-code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ministryofjustice/github-actions/code-formatter@ba54ac10474563ffb66fec0696b6199bf4c7a671 # Testing Version
        with:
            ignore-files: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
