name: "Format Code: ensure code formatting guidelines are met"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  format-code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: ministryofjustice/github-actions/code-formatter@ccee129b6753f0989d21a1050a58e94901853230 # Test Version
        with:
            ignore-files: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
